//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FISE_Browser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FISE_Browser.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user account has been disabled..
        /// </summary>
        public static string AccountHasDisabled {
            get {
                return ResourceManager.GetString("AccountHasDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration pending – complete that first.
        /// </summary>
        public static string AccountNotActive {
            get {
                return ResourceManager.GetString("AccountNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey! You have already attempted this activity! Would you like to see how it went last time?.
        /// </summary>
        public static string ActivityReviewMessage {
            get {
                return ResourceManager.GetString("ActivityReviewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar changed!.
        /// </summary>
        public static string Avatarchanged {
            get {
                return ResourceManager.GetString("Avatarchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a cool looking avatar to keep you company.
        /// </summary>
        public static string AvatarCompanyLine {
            get {
                return ResourceManager.GetString("AvatarCompanyLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change avatar - please try again after some time.
        /// </summary>
        public static string AvatarNotChanged {
            get {
                return ResourceManager.GetString("AvatarNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER.
        /// </summary>
        public static string ChangePassword_submit {
            get {
                return ResourceManager.GetString("ChangePassword_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE PASSWORD.
        /// </summary>
        public static string ChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2017 Parag.
        /// </summary>
        public static string CopyRightText {
            get {
                return ResourceManager.GetString("CopyRightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current &amp; New Password cannot be same..
        /// </summary>
        public static string CurrentNewPasswordSame {
            get {
                return ResourceManager.GetString("CurrentNewPasswordSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Customer_ChangePassword_error {
            get {
                return ResourceManager.GetString("Customer_ChangePassword_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is incorrect..
        /// </summary>
        public static string Customer_ChangePassword_oldPwdIncorrect {
            get {
                return ResourceManager.GetString("Customer_ChangePassword_oldPwdIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully..
        /// </summary>
        public static string Customer_ChangePassword_success {
            get {
                return ResourceManager.GetString("Customer_ChangePassword_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONE.
        /// </summary>
        public static string DoneButtonText {
            get {
                return ResourceManager.GetString("DoneButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER.
        /// </summary>
        public static string EnterButtonText {
            get {
                return ResourceManager.GetString("EnterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JUST EXPLORING?.
        /// </summary>
        public static string ExploreText {
            get {
                return ResourceManager.GetString("ExploreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORGOT LOGIN NAME.
        /// </summary>
        public static string ForgotId {
            get {
                return ResourceManager.GetString("ForgotId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot login ID or Password.
        /// </summary>
        public static string ForgotLinkText {
            get {
                return ResourceManager.GetString("ForgotLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FORGOT SECRET CODE.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directly.
        /// </summary>
        public static string HelpHeading1 {
            get {
                return ResourceManager.GetString("HelpHeading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Through email.
        /// </summary>
        public static string HelpHeading2 {
            get {
                return ResourceManager.GetString("HelpHeading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write your question here and hit send. Our Support team will respond soon by sending an email to the email id given for this account..
        /// </summary>
        public static string HelpPara1 {
            get {
                return ResourceManager.GetString("HelpPara1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you would like to send your question over an email, you can write to us at.
        /// </summary>
        public static string HelpPara2Part1 {
            get {
                return ResourceManager.GetString("HelpPara2Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@kitablet.in.
        /// </summary>
        public static string HelpPara2Part2 {
            get {
                return ResourceManager.GetString("HelpPara2Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpTabText {
            get {
                return ResourceManager.GetString("HelpTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string HiText {
            get {
                return ResourceManager.GetString("HiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDENTIFY YOURSELF!.
        /// </summary>
        public static string IdentifyYourself {
            get {
                return ResourceManager.GetString("IdentifyYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Parag Initiative.
        /// </summary>
        public static string InitiativeText {
            get {
                return ResourceManager.GetString("InitiativeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.kitablet.in.
        /// </summary>
        public static string KitabletIn {
            get {
                return ResourceManager.GetString("KitabletIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.kitablet.in/.
        /// </summary>
        public static string KitabletLink {
            get {
                return ResourceManager.GetString("KitabletLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER.
        /// </summary>
        public static string LoginBtn {
            get {
                return ResourceManager.GetString("LoginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two secret codes do not match - try again..
        /// </summary>
        public static string NewReNewDontMatch {
            get {
                return ResourceManager.GetString("NewReNewDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to the Server. Check your Internet Connection..
        /// </summary>
        public static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent log-in don’t work on Reader App.
        /// </summary>
        public static string NotAllowedToLogin {
            get {
                return ResourceManager.GetString("NotAllowedToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed!.
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change password - please try again after sometime.
        /// </summary>
        public static string PasswordNotChanged {
            get {
                return ResourceManager.GetString("PasswordNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Secret Code.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have atleast 6 characters..
        /// </summary>
        public static string PasswordStrength {
            get {
                return ResourceManager.GetString("PasswordStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following privacy policy forms part of the binding terms and conditions of use between FISE and administrator(s) of the Kitablet Digital Library. FISE shall not use any personal data except for the limited purpose of (i) performing their obligations under this agreement; (ii) improving the services provided hereunder; (iii) updating administrators and user members of the latest offerings available in the digital library. FISE shall have complete ownership of and unfettered discretion to use any and all  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PolicyPart1 {
            get {
                return ResourceManager.GetString("PolicyPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shall mean and include persons who can form legally binding contracts and registered as administrators having single or multiple user member account subscriptions to the Digital Library and who shall be wholly responsible and liable for all use of all such user accounts. All references to Administrator(s) in these terms and conditions shall mean and include the respective user members registered through such administrator..
        /// </summary>
        public static string PolicyPart2 {
            get {
                return ResourceManager.GetString("PolicyPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try another user name/password – no account with given.
        /// </summary>
        public static string PopupLogin_NoAccountError {
            get {
                return ResourceManager.GetString("PopupLogin_NoAccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription expired..
        /// </summary>
        public static string PopUpLogin_subscriptionExpired {
            get {
                return ResourceManager.GetString("PopUpLogin_subscriptionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! I was unable to log you in - can you try again?.
        /// </summary>
        public static string PopUpLogin_unknownError {
            get {
                return ResourceManager.GetString("PopUpLogin_unknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicyText {
            get {
                return ResourceManager.GetString("PrivacyPolicyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an Avatar.
        /// </summary>
        public static string SelectOneAvatar {
            get {
                return ResourceManager.GetString("SelectOneAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your email - we will reply soon..
        /// </summary>
        public static string ThankYouForFeedback {
            get {
                return ResourceManager.GetString("ThankYouForFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No books to show here - select a book to read!.
        /// </summary>
        public static string UACBookReadText {
            get {
                return ResourceManager.GetString("UACBookReadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin ID.
        /// </summary>
        public static string UserIDText {
            get {
                return ResourceManager.GetString("UserIDText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Username.
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn’t seem like your secret code - try again.
        /// </summary>
        public static string WrongCredentials {
            get {
                return ResourceManager.GetString("WrongCredentials", resourceCulture);
            }
        }
    }
}
