function getcities(){
	 var data= [
  {
    "id":"1",
    "city":"Ahmedabad",
    "state":"Gujarat",
    "country":"India"
  },
  {
    "id":"2",
    "city":"Bengaluru",
    "state":"Karnataka",
    "country":"India"
  },
  {
    "id":"3",
    "city":"Chennai",
    "state":"Tamil Nadu",
    "country":"India"
  },
  {
    "id":"4",
    "city":"Delhi",
    "state":"Delhi",
    "country":"India"
  },
  {
    "id":"5",
    "city":"Faridabad",
    "state":"Haryana",
    "country":"India"
  },
  {
    "id":"6",
    "city":"Ghaziabad",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"7",
    "city":"Gurgaon",
    "state":"Haryana",
    "country":"India"
  },
  {
    "id":"8",
    "city":"Mumbai",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"9",
    "city":"Noida",
    "state":"Uttar Pradesh",
    "country":"India"
  }
  ];
  /*,
  {
    "id":"10",
    "city":"Agartala",
    "state":"Tripura",
    "country":"India"
  },
  {
    "id":"11",
    "city":"Agra",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"12",
    "city":"Ahmednagar",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"13",
    "city":"Aizawl",
    "state":"Mizoram",
    "country":"India"
  },
  {
    "id":"14",
    "city":"Ajmer",
    "state":"Rajasthan",
    "country":"India"
  },
  {
    "id":"15",
    "city":"Akola",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"16",
    "city":"Alappuzha",
    "state":"Kerala",
    "country":"India"
  },
  {
    "id":"17",
    "city":"Aligarh",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"18",
    "city":"Allahabad",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"19",
    "city":"Alwar",
    "state":"Rajasthan",
    "country":"India"
  },
  {
    "id":"20",
    "city":"Ambala",
    "state":"Haryana",
    "country":"India"
  },
  {
    "id":"21",
    "city":"Ambattur",
    "state":"Tamil Nadu",
    "country":"India"
  },
  {
    "id":"22",
    "city":"Ambernath",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"23",
    "city":"Amravati",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"24",
    "city":"Amritsar",
    "state":"Punjab",
    "country":"India"
  },
  {
    "id":"25",
    "city":"Amroha",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"26",
    "city":"Anand",
    "state":"Gujarat",
    "country":"India"
  },
  {
    "id":"27",
    "city":"Anantapur",
    "state":"Andhra Pradesh",
    "country":"India"
  },
  {
    "id":"28",
    "city":"Arrah",
    "state":"Bihar",
    "country":"India"
  },
  {
    "id":"29",
    "city":"Asansol",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"30",
    "city":"Aurangabad",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"31",
    "city":"Avadi",
    "state":"Tamil Nadu",
    "country":"India"
  },
  {
    "id":"32",
    "city":"Baharampur",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"33",
    "city":"Bahraich",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"34",
    "city":"Bally",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"35",
    "city":"Baranagar",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"36",
    "city":"Barasat",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"37",
    "city":"Bardhaman",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"38",
    "city":"Bareilly",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"39",
    "city":"Bathinda",
    "state":"Punjab",
    "country":"India"
  },
  {
    "id":"40",
    "city":"Begusarai",
    "state":"Bihar",
    "country":"India"
  },
  {
    "id":"41",
    "city":"Belgaum",
    "state":"Karnataka",
    "country":"India"
  },
  {
    "id":"42",
    "city":"Bellary",
    "state":"Karnataka",
    "country":"India"
  },
  {
    "id":"43",
    "city":"Berhampur",
    "state":"Odisha",
    "country":"India"
  },
  {
    "id":"44",
    "city":"Bhagalpur",
    "state":"Bihar",
    "country":"India"
  },
  {
    "id":"45",
    "city":"Bhalswa Jahangir Pur",
    "state":"Delhi",
    "country":"India"
  },
  {
    "id":"46",
    "city":"Bharatpur",
    "state":"Rajasthan",
    "country":"India"
  },
  {
    "id":"47",
    "city":"Bhatpara",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"48",
    "city":"Bhavnagar",
    "state":"Gujarat",
    "country":"India"
  },
  {
    "id":"49",
    "city":"Bhilai",
    "state":"Chhattisgarh",
    "country":"India"
  },
  {
    "id":"50",
    "city":"Bhilwara",
    "state":"Rajasthan",
    "country":"India"
  },
  {
    "id":"51",
    "city":"Bhind",
    "state":"Madhya Pradesh",
    "country":"India"
  },
  {
    "id":"52",
    "city":"Bhiwandi",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"53",
    "city":"Bhiwani",
    "state":"Haryana",
    "country":"India"
  },
  {
    "id":"54",
    "city":"Bhopal",
    "state":"Madhya Pradesh",
    "country":"India"
  },
  {
    "id":"55",
    "city":"Bhubaneswar",
    "state":"Odisha",
    "country":"India"
  },
  {
    "id":"56",
    "city":"Bhusawal",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"57",
    "city":"Bidar",
    "state":"Karnataka",
    "country":"India"
  },
  {
    "id":"58",
    "city":"Bidhan Nagar",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"59",
    "city":"Bihar Sharif",
    "state":"Bihar",
    "country":"India"
  },
  {
    "id":"60",
    "city":"Bijapur",
    "state":"Karnataka",
    "country":"India"
  },
  {
    "id":"61",
    "city":"Bikaner",
    "state":"Rajasthan",
    "country":"India"
  },
  {
    "id":"62",
    "city":"Bilaspur",
    "state":"Chhattisgarh",
    "country":"India"
  },
  {
    "id":"63",
    "city":"Bokaro",
    "state":"Jharkhand",
    "country":"India"
  },
  {
    "id":"64",
    "city":"Bulandshahr",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"65",
    "city":"Burhanpur",
    "state":"Madhya Pradesh",
    "country":"India"
  },
  {
    "id":"66",
    "city":"Chandigarh",
    "state":"Chandigarh",
    "country":"India"
  },
  {
    "id":"67",
    "city":"Chandrapur",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"68",
    "city":"Chapra",
    "state":"Bihar",
    "country":"India"
  },
  {
    "id":"69",
    "city":"Chittoor",
    "state":"Andhra Pradesh",
    "country":"India"
  },
  {
    "id":"70",
    "city":"Coimbatore",
    "state":"Tamil Nadu",
    "country":"India"
  },
  {
    "id":"71",
    "city":"Cuttack",
    "state":"Odisha",
    "country":"India"
  },
  {
    "id":"72",
    "city":"Danapur",
    "state":"Bihar",
    "country":"India"
  },
  {
    "id":"73",
    "city":"Darbhanga",
    "state":"Bihar",
    "country":"India"
  },
  {
    "id":"74",
    "city":"Davanagere",
    "state":"Karnataka",
    "country":"India"
  },
  {
    "id":"75",
    "city":"Dehradun",
    "state":"Uttarakhand",
    "country":"India"
  },
  {
    "id":"76",
    "city":"Deoghar",
    "state":"Jharkhand",
    "country":"India"
  },
  {
    "id":"77",
    "city":"Dewas",
    "state":"Madhya Pradesh",
    "country":"India"
  },
  {
    "id":"78",
    "city":"Dhanbad",
    "state":"Jharkhand",
    "country":"India"
  },
  {
    "id":"79",
    "city":"Dhule",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"80",
    "city":"Dindigul",
    "state":"Tamil Nadu",
    "country":"India"
  },
  {
    "id":"81",
    "city":"Durg",
    "state":"Chhattisgarh",
    "country":"India"
  },
  {
    "id":"82",
    "city":"Durgapur",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"83",
    "city":"Eluru",
    "state":"Andhra Pradesh",
    "country":"India"
  },
  {
    "id":"84",
    "city":"English Bazar",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"85",
    "city":"Erode",
    "state":"Tamil Nadu",
    "country":"India"
  },
  {
    "id":"86",
    "city":"Etawah",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"87",
    "city":"Farrukhabad",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"88",
    "city":"Fatehpur",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"89",
    "city":"Firozabad",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"90",
    "city":"Gandhidham",
    "state":"Gujarat",
    "country":"India"
  },
  {
    "id":"91",
    "city":"Gandhinagar",
    "state":"Gujarat",
    "country":"India"
  },
  {
    "id":"92",
    "city":"Gaya",
    "state":"Bihar",
    "country":"India"
  },
  {
    "id":"93",
    "city":"Gopalpur",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"94",
    "city":"Gorakhpur",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"95",
    "city":"Gulbarga",
    "state":"Karnataka",
    "country":"India"
  },
  {
    "id":"96",
    "city":"Guna",
    "state":"Madhya Pradesh",
    "country":"India"
  },
  {
    "id":"97",
    "city":"Guntur",
    "state":"Andhra Pradesh",
    "country":"India"
  },
  {
    "id":"98",
    "city":"Guwahati",
    "state":"Assam",
    "country":"India"
  },
  {
    "id":"99",
    "city":"Gwalior",
    "state":"Madhya Pradesh",
    "country":"India"
  },
  {
    "id":"100",
    "city":"Haldia",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"101",
    "city":"Hapur",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"102",
    "city":"Haridwar",
    "state":"Uttarakhand",
    "country":"India"
  },
  {
    "id":"103",
    "city":"Hospet",
    "state":"Karnataka",
    "country":"India"
  },
  {
    "id":"104",
    "city":"Howrah",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"105",
    "city":"Hubballi-Dharwad",
    "state":"Karnataka",
    "country":"India"
  },
  {
    "id":"106",
    "city":"Hugli and Chinsurah",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"107",
    "city":"Hyderabad",
    "state":"Telangana",
    "country":"India"
  },
  {
    "id":"108",
    "city":"Ichalkaranji",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"109",
    "city":"Imphal",
    "state":"Manipur",
    "country":"India"
  },
  {
    "id":"110",
    "city":"Indore",
    "state":"Madhya Pradesh",
    "country":"India"
  },
  {
    "id":"111",
    "city":"Jabalpur",
    "state":"Madhya Pradesh",
    "country":"India"
  },
  {
    "id":"112",
    "city":"Jaipur",
    "state":"Rajasthan",
    "country":"India"
  },
  {
    "id":"113",
    "city":"Jalandhar",
    "state":"Punjab",
    "country":"India"
  },
  {
    "id":"114",
    "city":"Jalgaon",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"115",
    "city":"Jalna",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"116",
    "city":"Jammu",
    "state":"Jammu and Kashmir",
    "country":"India"
  },
  {
    "id":"117",
    "city":"Jamnagar",
    "state":"Gujarat",
    "country":"India"
  },
  {
    "id":"118",
    "city":"Jamshedpur",
    "state":"Jharkhand",
    "country":"India"
  },
  {
    "id":"119",
    "city":"Jaunpur",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"120",
    "city":"Jhansi",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"121",
    "city":"Jodhpur",
    "state":"Rajasthan",
    "country":"India"
  },
  {
    "id":"122",
    "city":"Junagadh",
    "state":"Gujarat",
    "country":"India"
  },
  {
    "id":"123",
    "city":"Kadapa",
    "state":"Andhra Pradesh",
    "country":"India"
  },
  {
    "id":"124",
    "city":"Kakinada",
    "state":"Andhra Pradesh",
    "country":"India"
  },
  {
    "id":"125",
    "city":"Kalyan-Dombivali",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"126",
    "city":"Kamarhati",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"127",
    "city":"Kanpur",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"128",
    "city":"Karaikudi",
    "state":"Tamil Nadu",
    "country":"India"
  },
  {
    "id":"129",
    "city":"Karawal Nagar",
    "state":"Delhi",
    "country":"India"
  },
  {
    "id":"130",
    "city":"Karimnagar",
    "state":"Telangana",
    "country":"India"
  },
  {
    "id":"131",
    "city":"Karnal",
    "state":"Haryana",
    "country":"India"
  },
  {
    "id":"132",
    "city":"Katihar",
    "state":"Bihar",
    "country":"India"
  },
  {
    "id":"133",
    "city":"Khammam",
    "state":"Telangana",
    "country":"India"
  },
  {
    "id":"134",
    "city":"Khandwa",
    "state":"Madhya Pradesh",
    "country":"India"
  },
  {
    "id":"135",
    "city":"Kharagpur",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"136",
    "city":"Khora",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"137",
    "city":"Kirari Suleman Nagar",
    "state":"Delhi",
    "country":"India"
  },
  {
    "id":"138",
    "city":"Kochi",
    "state":"Kerala",
    "country":"India"
  },
  {
    "id":"139",
    "city":"Kolhapur",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"140",
    "city":"Kolkata",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"141",
    "city":"Kollam",
    "state":"Kerala",
    "country":"India"
  },
  {
    "id":"142",
    "city":"Korba",
    "state":"Chhattisgarh",
    "country":"India"
  },
  {
    "id":"143",
    "city":"Kota",
    "state":"Rajasthan",
    "country":"India"
  },
  {
    "id":"144",
    "city":"Kottayam",
    "state":"Kerala",
    "country":"India"
  },
  {
    "id":"145",
    "city":"Kozhikode",
    "state":"Kerala",
    "country":"India"
  },
  {
    "id":"146",
    "city":"Kulti",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"147",
    "city":"Kurnool",
    "state":"Andhra Pradesh",
    "country":"India"
  },
  {
    "id":"148",
    "city":"Latur",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"149",
    "city":"Loni",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"150",
    "city":"Lucknow",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"151",
    "city":"Ludhiana",
    "state":"Punjab",
    "country":"India"
  },
  {
    "id":"152",
    "city":"Madhyamgram",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"153",
    "city":"Madurai",
    "state":"Tamil Nadu",
    "country":"India"
  },
  {
    "id":"154",
    "city":"Mahesana",
    "state":"Gujarat",
    "country":"India"
  },
  {
    "id":"155",
    "city":"Maheshtala",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"156",
    "city":"Malegaon",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"157",
    "city":"Mangalore",
    "state":"Karnataka",
    "country":"India"
  },
  {
    "id":"158",
    "city":"Mango",
    "state":"Jharkhand",
    "country":"India"
  },
  {
    "id":"159",
    "city":"Mathura",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"160",
    "city":"Mau",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"161",
    "city":"Meerut",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"162",
    "city":"Mira-Bhayandar",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"163",
    "city":"Mirzapur",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"164",
    "city":"Moradabad",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"165",
    "city":"Morena",
    "state":"Madhya Pradesh",
    "country":"India"
  },
  {
    "id":"166",
    "city":"Morvi",
    "state":"Gujarat",
    "country":"India"
  },
  {
    "id":"167",
    "city":"Munger",
    "state":"Bihar",
    "country":"India"
  },
  {
    "id":"168",
    "city":"Murwara",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"169",
    "city":"Muzaffarnagar",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"170",
    "city":"Muzaffarpur",
    "state":"Bihar",
    "country":"India"
  },
  {
    "id":"171",
    "city":"Mysore",
    "state":"Karnataka",
    "country":"India"
  },
  {
    "id":"172",
    "city":"Nadiad",
    "state":"Gujarat",
    "country":"India"
  },
  {
    "id":"173",
    "city":"Nagarcoil",
    "state":"Tamil Nadu",
    "country":"India"
  },
  {
    "id":"174",
    "city":"Nagpur",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"175",
    "city":"Naihati",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"176",
    "city":"Nanded",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"177",
    "city":"Nandyal",
    "state":"Andhra Pradesh",
    "country":"India"
  },
  {
    "id":"178",
    "city":"Nangloi Jat",
    "state":"Delhi",
    "country":"India"
  },
  {
    "id":"179",
    "city":"Nashik",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"180",
    "city":"Nellore",
    "state":"Andhra Pradesh",
    "country":"India"
  },
  {
    "id":"181",
    "city":"Nizamabad",
    "state":"Telangana",
    "country":"India"
  },
  {
    "id":"182",
    "city":"North Dumdum",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"183",
    "city":"Ongole",
    "state":"Andhra Pradesh",
    "country":"India"
  },
  {
    "id":"184",
    "city":"Orai",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"185",
    "city":"Ozhukarai",
    "state":"Puducherry",
    "country":"India"
  },
  {
    "id":"186",
    "city":"Pali",
    "state":"Rajasthan",
    "country":"India"
  },
  {
    "id":"187",
    "city":"Pallavaram",
    "state":"Tamil Nadu",
    "country":"India"
  },
  {
    "id":"188",
    "city":"Panchkula",
    "state":"Haryana",
    "country":"India"
  },
  {
    "id":"189",
    "city":"Panihati",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"190",
    "city":"Panipat",
    "state":"Haryana",
    "country":"India"
  },
  {
    "id":"191",
    "city":"Panvel",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"192",
    "city":"Parbhani",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"193",
    "city":"Patiala",
    "state":"Punjab",
    "country":"India"
  },
  {
    "id":"194",
    "city":"Patna",
    "state":"Bihar",
    "country":"India"
  },
  {
    "id":"195",
    "city":"Pimpri-Chinchwad",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"196",
    "city":"Puducherry",
    "state":"Puducherry",
    "country":"India"
  },
  {
    "id":"197",
    "city":"Pune",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"198",
    "city":"Purnia",
    "state":"Bihar",
    "country":"India"
  },
  {
    "id":"199",
    "city":"Rae Bareli",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"200",
    "city":"Raichur",
    "state":"Karnataka",
    "country":"India"
  },
  {
    "id":"201",
    "city":"Raiganj",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"202",
    "city":"Raipur",
    "state":"Chhattisgarh",
    "country":"India"
  },
  {
    "id":"203",
    "city":"Rajahmundry",
    "state":"Andhra Pradesh",
    "country":"India"
  },
  {
    "id":"204",
    "city":"Rajkot",
    "state":"Gujarat",
    "country":"India"
  },
  {
    "id":"205",
    "city":"Rajpur Sonarpur",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"206",
    "city":"Ramagundam",
    "state":"Telangana",
    "country":"India"
  },
  {
    "id":"207",
    "city":"Rampur",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"208",
    "city":"Ranchi",
    "state":"Jharkhand",
    "country":"India"
  },
  {
    "id":"209",
    "city":"Ratlam",
    "state":"Madhya Pradesh",
    "country":"India"
  },
  {
    "id":"210",
    "city":"Raurkela Industrial Township",
    "state":"Odisha",
    "country":"India"
  },
  {
    "id":"211",
    "city":"Rewa",
    "state":"Madhya Pradesh",
    "country":"India"
  },
  {
    "id":"212",
    "city":"Rohtak",
    "state":"Haryana",
    "country":"India"
  },
  {
    "id":"213",
    "city":"Rourkela",
    "state":"Odisha",
    "country":"India"
  },
  {
    "id":"214",
    "city":"Rourkela",
    "state":"Odisha",
    "country":"India"
  },
  {
    "id":"215",
    "city":"Sagar",
    "state":"Madhya Pradesh",
    "country":"India"
  },
  {
    "id":"216",
    "city":"Saharanpur",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"217",
    "city":"Salem",
    "state":"Tamil Nadu",
    "country":"India"
  },
  {
    "id":"218",
    "city":"Sambalpur",
    "state":"Odisha",
    "country":"India"
  },
  {
    "id":"219",
    "city":"Sambalpur",
    "state":"Orissa",
    "country":"India"
  },
  {
    "id":"220",
    "city":"Sambhal",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"221",
    "city":"Sangli-Miraj & Kupwad",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"222",
    "city":"Satara",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"223",
    "city":"Satna",
    "state":"Madhya Pradesh",
    "country":"India"
  },
  {
    "id":"224",
    "city":"Secunderabad",
    "state":"Andhra Pradesh",
    "country":"India"
  },
  {
    "id":"225",
    "city":"Serampore",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"226",
    "city":"Shahjahanpur",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"227",
    "city":"Shimla",
    "state":"Himachal Pradesh",
    "country":"India"
  },
  {
    "id":"228",
    "city":"Shivamogga",
    "state":"Karnataka",
    "country":"India"
  },
  {
    "id":"229",
    "city":"Shivpuri",
    "state":"Madhya Pradesh",
    "country":"India"
  },
  {
    "id":"230",
    "city":"Sikar",
    "state":"Rajasthan",
    "country":"India"
  },
  {
    "id":"231",
    "city":"Siliguri",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"232",
    "city":"Singrauli",
    "state":"Madhya Pradesh",
    "country":"India"
  },
  {
    "id":"233",
    "city":"Sirsa",
    "state":"Haryana",
    "country":"India"
  },
  {
    "id":"234",
    "city":"Solapur",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"235",
    "city":"Sonipat",
    "state":"Haryana",
    "country":"India"
  },
  {
    "id":"236",
    "city":"South Dumdum",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"237",
    "city":"Sri Ganganagar",
    "state":"Rajasthan",
    "country":"India"
  },
  {
    "id":"238",
    "city":"Srinagar",
    "state":"Jammu and Kashmir",
    "country":"India"
  },
  {
    "id":"239",
    "city":"Sultan Pur Majra",
    "state":"Delhi",
    "country":"India"
  },
  {
    "id":"240",
    "city":"Surat",
    "state":"Gujarat",
    "country":"India"
  },
  {
    "id":"241",
    "city":"Surendranagar Dudhrej",
    "state":"Gujarat",
    "country":"India"
  },
  {
    "id":"242",
    "city":"Thane",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"243",
    "city":"Thanjavur",
    "state":"Tamil Nadu",
    "country":"India"
  },
  {
    "id":"244",
    "city":"Thiruvananthapuram",
    "state":"Kerala",
    "country":"India"
  },
  {
    "id":"245",
    "city":"Thoothukudi",
    "state":"Tamil Nadu",
    "country":"India"
  },
  {
    "id":"246",
    "city":"Thrissur",
    "state":"Kerala",
    "country":"India"
  },
  {
    "id":"247",
    "city":"Tiruchirappalli",
    "state":"Tamil Nadu",
    "country":"India"
  },
  {
    "id":"248",
    "city":"Tirunelveli",
    "state":"Tamil Nadu",
    "country":"India"
  },
  {
    "id":"249",
    "city":"Tirupati",
    "state":"Andhra Pradesh",
    "country":"India"
  },
  {
    "id":"250",
    "city":"Tiruppur",
    "state":"Tamil Nadu",
    "country":"India"
  },
  {
    "id":"251",
    "city":"Tiruvottiyur",
    "state":"Tamil Nadu",
    "country":"India"
  },
  {
    "id":"252",
    "city":"Tumkur",
    "state":"Karnataka",
    "country":"India"
  },
  {
    "id":"253",
    "city":"Udaipur",
    "state":"Rajasthan",
    "country":"India"
  },
  {
    "id":"254",
    "city":"Ujjain",
    "state":"Madhya Pradesh",
    "country":"India"
  },
  {
    "id":"255",
    "city":"Ulhasnagar",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"256",
    "city":"Uluberia",
    "state":"West Bengal",
    "country":"India"
  },
  {
    "id":"257",
    "city":"Unnao",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"258",
    "city":"Vadodara",
    "state":"Gujarat",
    "country":"India"
  },
  {
    "id":"259",
    "city":"Varanasi",
    "state":"Uttar Pradesh",
    "country":"India"
  },
  {
    "id":"260",
    "city":"Vasai-Virar",
    "state":"Maharashtra",
    "country":"India"
  },
  {
    "id":"261",
    "city":"Vellore",
    "state":"Tamil Nadu",
    "country":"India"
  },
  {
    "id":"262",
    "city":"Vijayanagaram",
    "state":"Andhra Pradesh",
    "country":"India"
  },
  {
    "id":"263",
    "city":"Vijayawada",
    "state":"Andhra Pradesh",
    "country":"India"
  },
  {
    "id":"264",
    "city":"Visakhapatnam",
    "state":"Andhra Pradesh",
    "country":"India"
  },
  {
    "id":"265",
    "city":"Warangal",
    "state":"Telangana",
    "country":"India"
  },
  {
    "id":"266",
    "city":"Yamunanagar",
    "state":"Haryana",
    "country":"India"
  }*/

 var finaldata=data.reduce(function(result, current,i) {
        result[current.state] = result[current.state] || [];
        result[current.state].push(current);
        return result;
    }, {});
	return  finaldata;  
}